LKF_BASE_PATH=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
LKF_WORKDIR="${LKF_BASE_PATH}/work"

# For LLVM
LKF_LLVM_VERSION="18.1.8"
LKF_LLVM_BUILD_DIR="${LKF_WORKDIR}/llvm-build"
LKF_LLVM_INSTALL_DIR="${LKF_WORKDIR}/opt/llvm-${LKF_LLVM_VERSION}"
LKF_LLVM_SRC_UNPACK_DIR="${LKF_LLVM_BUILD_DIR}/llvm-project-llvmorg-${LKF_LLVM_VERSION}"

# For Linux kernel
LKF_LINUX_KERNEL_BUILD_ARTIFACT_DIR="${LKF_WORKDIR}/linux-kernel-artifacts"
LKF_CFG_FILES_OUTPUT_DIR="${LKF_LINUX_KERNEL_BUILD_ARTIFACT_DIR}/dot-files"