LKF_BASE_PATH=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
LKF_WORKDIR="${LKF_BASE_PATH}/work"

# For LLVM
LKF_LLVM_VERSION="15.0.7"
LKF_LLVM_BUILD_DIR="${LKF_WORKDIR}/llvm-build"
LKF_LLVM_INSTALL_DIR="${LKF_WORKDIR}/opt/llvm-${LKF_LLVM_VERSION}"
LKF_LLVM_SRC_UNPACK_DIR="${LKF_LLVM_BUILD_DIR}/llvm-project-llvmorg-${LKF_LLVM_VERSION}"
LKF_CLANG="${LKF_LLVM_INSTALL_DIR}/bin/clang"

# IRDumper
IRDUMPER="${LKF_BASE_PATH}/IRDumper/build/lib/libDumper.so"

# DeepType
DEEPTYPE_DIR="${LKF_BASE_PATH}/DeepType"

# For Linux kernel
LKF_LINUX_KERNEL_BUILD_SCRIPT_DIR="${LKF_BASE_PATH}/kernel"

# syskaller
SYZKALLER_DIR="${LKF_WORKDIR}/syzkaller"
DEBIAN_IMAGE_DIR="${LKF_WORKDIR}/image"
DEBIAN_CODENAME="bookworm"
DEBIAN_ARCH="x86_64"

